### PR TITLE
Endpoint to change account password

### LINKED ISSUE #83: Reset password endpoint
Create endpoint to handle account password changes

### PR DESCRIPTION
**Pull request by gilhrpenner**
# What I did
- Created route to change password
- Small symbol renaming for better readability
- Updated swagger documentation
  - Added documentation for sign-in which was forgotten
  - Added documentation for password reset
- Moved create account route from /account to /auth so /account can always ensure authentication
- Create unit tests for ChangePasswordService

Closes #83

### CODE REVIEW

**Comment by akashd50** [comment]
Since Brett's stuff is in, do you wanna change this pr to actually update the db or would you rather it be in a separate pr? Upto you I guess!

**Comment by gilhrpenner** [comment]
> 

Good catch, I will do this sometime tonight :)

**Review by BrettDowneyuofm — APPROVED** [review]

**Comment by BrettDowneyuofm** [comment]
Looks good so far 👍

**Review by MarkRobitaille — APPROVED** [review]
Looks good to me! I'm assuming the implementation of the `updatePassword` method will be a separate dev task?

**Comment by gilhrpenner** [comment]
Originally the db wasn't implemented so that's why I didn't implement this logic.

Now the db is already merged, but because y'all have approved this PR I'll do it in a different task

**Pull request merged**
