### PR TITLE
Setup Database Schema

### LINKED ISSUE #35: Setup Database Schema
Initialize the database with a schema that will support the (minimum) following entities:

- Users
- Listings
- Messages
- Listing Photos

### PR DESCRIPTION
**Pull request by BrettDowneyuofm**
# What I did
- Setup MariaDB and Prisma schema for the following entities:
- Users
- Listings
- Listing Photos
- Messages

Closes #35

### CODE REVIEW

**Review by gilhrpenner — COMMENTED** [review]
Hey, shouldn't we be using migrations for that?

**Review by akashd50 — APPROVED** [review]

**Comment by BrettDowneyuofm** [comment]
> Hey, shouldn't we be using migrations for that?

Migrations are used to make DB changes in production not during development.

**Comment by gilhrpenner** [comment]
> > Hey, shouldn't we be using migrations for that?
> 
> Migrations are used to make DB changes in production not during development.

hmmn, ok.
My previous work terms we started using migrations even for projects in development and not released yet, but I guess that's fine for now

**Review by gilhrpenner — APPROVED** [review]

**Comment by BrettDowneyuofm** [comment]
> > > Hey, shouldn't we be using migrations for that?
> > 
> > 
> > Migrations are used to make DB changes in production not during development.
> 
> hmmn, ok. My previous work terms we started using migrations even for projects in development and not released yet, but I guess that's fine for now

I've done the opposite and have been told to revert migrations at previous work terms in this situation. It will create unnecessary complexity, when we are simply defining the base data model. Are there any benefits to migrating during the development of the initial data model? As far as I know, the primary benefit of using a migration is to protect the existing data when making schema changes, however since we do not have any existing data using migrations here simply adds extra complexity.

**Comment by gilhrpenner** [comment]
Yeah, it does make sense.
I agree with what you said and never questioned before why doing that so early on.

**Comment by BrettDowneyuofm** [comment]
> Yeah, it does make sense. I agree with what you said and never questioned before why doing that so early on.

I think we should look into using migrations for when we start to host the application. Also we may be able to integrate automatic migrations to the production database in the CI/CD pipeline, though we will have to look into that

**Review by MarkRobitaille — APPROVED** [review]
Looks good to me! Matches what we went through in our meeting 👍

**Pull request merged**
