### PR TITLE
Removed files from main directory closes #29

### LINKED ISSUE #29: Main directory cleanup
Files from the frontend app were left behind in the main directory, needs to be removed.

### PR DESCRIPTION
**Pull request by gilhrpenner**
When I created the frontend project I forgot to create it inside a frontend folder and those files were left behind when I moved things to its proper location.

### CODE REVIEW

**Review by BrettDowneyuofm — APPROVED** [review]
Looks good to merge 🎉

**Review by MarkRobitaille — COMMENTED** [review]
This seems to remove some of the README stuff at the bottom. I'm not sure if that was automatically generated stuff appended to our README to begin with, but I figured I should bring it up if we want that there.

**Comment by gilhrpenner** [comment]
Yes, that's correct.

It was auto generated by Quasar when creating a project, don't need it.

**Review by MarkRobitaille — APPROVED** [review]
Looks good to me. 👍

**Pull request merged**
