### PR TITLE
Quasar SPA setup

### PR DESCRIPTION
**Pull request by gilhrpenner**
Initial setup with file formatting.

Need to remove unnecessary default components but left them there, just for future reference for new Vue users.

### CODE REVIEW

**Comment by BrettDowneyuofm** [comment]
Looks good to me

**Review by MarkRobitaille — CHANGES_REQUESTED** [review]
I think we should put the front end code into its own folder. Otherwise, looks good to me.

**Comment by gilhrpenner** [comment]
> I think we should put the front end code into its own folder. Otherwise, looks good to me.

Good catch! I can't believe I missed that.
Thanks for being such a great reviewer.

**Review by MarkRobitaille — APPROVED** [review]
Looks good now! Thanks for making those changes. 😄

**Pull request merged**
